---
date: "`r Sys.Date()`"
output: 
  html_document: 
    theme: null
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=F, warning=FALSE, message=FALSE}
library(tidyverse)
library(knitr)
library(DT)
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, print=FALSE, verbose=TRUE)
opts_chunk$set(results="asis")
opts_chunk$set(cache=TRUE,cache.path="cache/")
opts_chunk$set(fig.path="figure/",dev=c("png", "svg"))
opts_chunk$set(debug = function(before, options, envir) {
    if (!before) {
        message(
            paste(names(envir), as.list(envir),
                  sep = " = ", collapse = "\n"))
    }
})

presentation <- theme(axis.text.x = element_text(size=14, face="bold", color="black"),
                      axis.text.y = element_text(size=14, face="bold", color="black"),
                      axis.title.x = element_text(size=18, face="bold", color="black", vjust=-1),
                      axis.title.y = element_text(size=18, face="bold", color="black", vjust=2),
                      strip.text.x = element_text(size=18, face="bold", color="black"),
                      strip.text.y = element_text(size=18, face="bold", color="black"),
                      panel.spacing = unit(0.50, "lines"),
                      plot.margin  = unit(c(1,1,1,1), "cm"),
                      plot.title   = element_text(size=24, face="bold",vjust=2),
                      legend.position="none")


```

```{r load}
STRAIN_PATH <- glue::glue("_aggregate/multiqc/strain_data/")

sample_sheet <- data.table::fread(glue::glue("sample_sheet.tsv"))

total_strains <- length(unique(sample_sheet$strain))
total_sequenced_libraries <- nrow(unique(sample_sheet[, c("strain", "id")]))



# Load coverage data
mapped_cov <- data.table::fread(fs::path_join(c(STRAIN_PATH, "mqc_mosdepth-coverage-per-contig_1.txt"))) 

mapped_cov$coverage <- rowMeans(mapped_cov[,c("I", "II", "III", "IV", "V")], na.rm=TRUE)

# Load Samtools stats
mapped_stats <- data.table::fread(fs::path_join(c(STRAIN_PATH, "multiqc_samtools_stats.txt"))) 

mapped <- dplyr::select(mapped_stats, Sample, raw_total_sequences, reads_mapped, reads_mapped_percent) %>% 
    dplyr::mutate(raw_total_sequences = round(raw_total_sequences/1000000, 2)) %>%
    dplyr::mutate(reads_mapped = round(reads_mapped/1000000, 2)) %>% 
    dplyr::mutate(reads_mapped_percent = round(reads_mapped_percent, 1)) %>%
    dplyr::inner_join(select(mapped_cov, Sample, coverage)) %>% 
    dplyr::mutate(coverage = round(coverage)) %>% 
    dplyr::arrange(Sample)


median_table <- data.frame(raw_total_sequences = median(mapped$raw_total_sequences), 
                           reads_mapped = median(mapped$reads_mapped), 
                           reads_mapped_percent = median(mapped$reads_mapped_percent),
                           coverage = median(mapped$coverage)) 
```

## Overview

* __Total strains__ - `r total_strains`
* __Sequenced libraries__ - `r total_sequenced_libraries`
* __Median mapped reads__ - `r round((median_table$reads_mapped)) ` million
* __Median coverage__ - `r median_table$coverage`

## Reads Mapped by Strain

```{r reads_mapped_by_strain}
datatable(mapped, colnames=c("Strain", "Total Reads (M)", "Mapped Reads (M)", "Percent Mapped", "Coverage (x)"), options = list(pageLength = 50))

data.table::fwrite(mapped, "alignment_stats.tsv")
```

Download [mapped_reads.tsv](data/alignment_stats.tsv)

## Distribution of stats

```{r mapped_read_percent, fig.width=8, fig.height=6}

mapped_long <- mapped %>% select(-Sample) %>% gather() %>% 
    mutate(key_f = factor(key, levels = c("raw_total_sequences", "reads_mapped", "reads_mapped_percent", "coverage")))

median_long <- median_table %>% gather() %>% 
    mutate(key_f = factor(key, levels = c("raw_total_sequences", "reads_mapped", "reads_mapped_percent", "coverage"))) %>% 
    mutate(value_2dig = format(round(value,2), nsmall=2))


ggplot(mapped_long) + 
    geom_histogram(aes(x = value), fill = "#A9A9A9") +
    facet_wrap(~key_f, scales = "free",     labeller = labeller(
        key_f = c(    "raw_total_sequences" = "Total Reads (M)",
                      "reads_mapped" = "Mapped Reads (M)",
                      "reads_mapped_percent" = "Percent Mapped",
                      "coverage" = "Coverage (x)"))) +
    geom_vline(data=median_long, aes(xintercept=value), color = "red") +
    geom_text(data=median_long, aes(x = Inf, y = Inf,
                                    label=paste0("median ", value_2dig),
                                    vjust = 1.6, hjust = 1.6),
              colour="red",
              text=element_text(size=16)) +
    xlab("") + ylab("Number of strains") +
    theme_bw() +
    presentation 


```
